### ISSUE TITLE
Error while running `fbc_curation_examples`

### ISSUE THREAD

**Issue by karthikraman** [matthiaskoenig/fbc_curation#34]
Hi! I get the following error while trying to run `fbc_curation_examples`. Any issues with my installation?

```
karthik@uranium:~$ fbc_curation_examples
/home/karthik/.local/lib/python3.6/site-packages/sympy/__init__.py:676: SymPyDeprecationWarning:

importing sympy.core.singleton with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.singleton instead.
See https://github.com/sympy/sympy/issues/18245 for more info.

  deprecated_since_version="1.6").warn()
/usr/local/lib/python3.6/dist-packages/cameo/visualization/plotting/__init__.py:52: UserWarning: Cannot import any plotting library. Please install one of 'plotly', 'bokeh' or 'ggplot' if you want to use any plotting function.
  warn("Cannot import any plotting library. Please install one of 'plotly', 'bokeh' or 'ggplot' if you want to"
################################################################################
/usr/local/lib/python3.6/examples/models/e_coli_core.xml
################################################################################
Traceback (most recent call last):
  File "/usr/local/bin/fbc_curation_examples", line 8, in <module>
    sys.exit(run_examples())
  File "/usr/local/lib/python3.6/dist-packages/fbc_curation/examples.py", line 13, in run_examples
    example_ecoli_core(results_path=results_path / "e_coli_core")
  File "/usr/local/lib/python3.6/dist-packages/fbc_curation/examples.py", line 21, in example_ecoli_core
    EXAMPLE_PATH / "models" / "e_coli_core.xml", results_path=results_path
  File "/usr/local/lib/python3.6/dist-packages/fbc_curation/examples.py", line 44, in _run_example
    obj_info = Curator.read_objective_information(model_path)
  File "/usr/local/lib/python3.6/dist-packages/fbc_curation/curator/curator.py", line 151, in read_objective_information
    fbc_model = model.getPlugin("fbc")  # type: libsbml.FbcModelPlugin
AttributeError: 'NoneType' object has no attribute 'getPlugin'
```

**Comment by matthiaskoenig** [comment]
Sorry this with a problem with packaging the examples on pypi. I just released a bugfix release `0.1.6` which fixes the issue.
Just do a 
```
pip install fbc_curation --upgrade
```
Best Matthias

**Comment by karthikraman** [comment]
I get another error now, based on permissions:
```
* CuratorCobrapy: reaction_deletion
Traceback (most recent call last):
  File "/usr/local/bin/fbc_curation_examples", line 8, in <module>
    sys.exit(run_examples())
  File "/usr/local/lib/python3.6/dist-packages/fbc_curation/examples.py", line 13, in run_examples
    example_ecoli_core(results_path=results_path / "e_coli_core")
  File "/usr/local/lib/python3.6/dist-packages/fbc_curation/examples.py", line 21, in example_ecoli_core
    EXAMPLE_PATH / "models" / "e_coli_core.xml", results_path=results_path
  File "/usr/local/lib/python3.6/dist-packages/fbc_curation/examples.py", line 52, in _run_example
    results.write_results(results_path / curator_keys[k])
  File "/usr/local/lib/python3.6/dist-packages/fbc_curation/curator/results.py", line 91, in write_results
    with open(path_out / CuratorConstants.METADATA_FILENAME, "w") as f_json:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/fbc_curation/examples/results/e_coli_core/cobrapy/metadata.json'
```

Can it just throw a warning that the directory is not writeable, and write to `/tmp/` or something? That way, when someone downloads and runs the examples, they just work "out of the box". 

Thanks again for putting this together -- works beautifully!

**Comment by karthikraman** [comment]
Of course running `sudo fbc_curation_examples` works.

**Comment by matthiaskoenig** [comment]
Sorry for that. The example files are distributed with the installed package. So if you need permissions for the folders you have to use sudo :/. I would recommend to create a virtual environment which has user permissions and also isolates the environment from the systems python.
Alternatively you could install with pip in user space then you can run without sudo.
