### ISSUE TITLE
Issue with COVID model

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/fbc_curation#56]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/src/fbc_curation/worker.py", line 84, in frog_task
    report.to_tsvs_with_metadata(tmp_path)
  File "/code/src/fbc_curation/frog.py", line 306, in to_tsvs_with_metadata
    df.sort_values(by=["gene"], inplace=True)
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 6259, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 1779, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'gene'
```

**Comment by matthiaskoenig** [comment]
There are no genes in the model, so gene deletions fail.
