### ISSUE TITLE
Bug when running FROG: cannot import name 'soft_unicode' from 'markupsafe' 

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/fbc_curation#69]
```
Traceback (most recent call last):
  File "/home/mkoenig/envs/fbc-curation/bin/fbc_curation", line 8, in <module>
    sys.exit(main())
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/fbc_curation/curation.py", line 144, in main
    from fbc_curation.curator.cameo_curator import CuratorCameo
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/fbc_curation/curator/cameo_curator.py", line 8, in <module>
    from cameo import __version__ as cameo_version
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/cameo/__init__.py", line 97, in <module>
    from .flux_analysis.analysis import flux_variability_analysis, phenotypic_phase_plane
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/cameo/flux_analysis/__init__.py", line 18, in <module>
    from .simulation import *
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/cameo/flux_analysis/simulation.py", line 43, in <module>
    from cameo.visualization.palette import mapper, Palette
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/cameo/visualization/__init__.py", line 17, in <module>
    from .visualization import *
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/cameo/visualization/visualization.py", line 28, in <module>
    from escher import Builder
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/escher/__init__.py", line 11, in <module>
    from escher.plots import (
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/escher/plots.py", line 20, in <module>
    from jinja2 import Environment, PackageLoader, Template
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/mkoenig/envs/fbc-curation/lib/python3.8/site-packages/markupsafe/__init__.py)
```

**Comment by matthiaskoenig** [comment]
Solved with dependency updates
