### ISSUE TITLE
Unbound errors in biomodels in FVA

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/fbc_curation#8]
see https://www.ebi.ac.uk/biomodels/MODEL1709260000

**Comment by matthiaskoenig** [comment]
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/mkoenig/envs/fbc_curation/lib/python3.6/site-packages/cobra/flux_analysis/variability.py", line 48, in _fva_step
    sutil.check_solver_status(_model.solver.status)
  File "/home/mkoenig/envs/fbc_curation/lib/python3.6/site-packages/cobra/util/solver.py", line 421, in check_solver_status
    raise OptimizationError("solver status is '{}'".format(status))
cobra.exceptions.OptimizationError: solver status is 'unbounded'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mkoenig/envs/fbc_curation/bin/fbc_curation", line 11, in <module>
    load_entry_point('fbc-curation', 'console_scripts', 'fbc_curation')()
  File "/home/mkoenig/git/fbc_curation/fbc_curation/fbc_files.py", line 199, in main
    create_fbc_files(results_dir=output_path, model_path=model_path)
  File "/home/mkoenig/git/fbc_curation/fbc_curation/fbc_files.py", line 47, in create_fbc_files
    decimals=decimals)
  File "/home/mkoenig/git/fbc_curation/fbc_curation/fbc_files.py", line 92, in create_fva_file
    df = flux_variability_analysis(model, model.reactions)
  File "/home/mkoenig/envs/fbc_curation/lib/python3.6/site-packages/cobra/flux_analysis/variability.py", line 221, in flux_variability_analysis
    _fva_step, reaction_ids, chunksize=chunk_size
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 347, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
cobra.exceptions.OptimizationError: solver status is 'unbounded'
```

**Comment by matthiaskoenig** [comment]
The model contains many other issues. For instance the gene associations (GPRs) are not parsed correctly with cobrapy.
